### ISSUE TITLE
code

### ISSUE THREAD

**Issue by alfadex** [superzerg/TCD1304AP_teensy2pp#2]
Hi , can code be changed so that controlling a nema 17 motor with a4988 for controling strech motor to a filament extuder?

**Comment by superzerg** [comment]
There are plenty of examples on how to control a a4988 with an arduino ( http://howtomechatronics.com/tutorials/arduino/how-to-control-stepper-motor-with-a4988-driver-and-arduino/ for example). That part is quite trivial.

You probably want to make a feedback from the width measured by the sensor to the speed of the stretch motor.That should be straightforward as well. 

However the settings (initial speed, PID coefficients, ... ) will greatly depends on the setup, so the parameter must be easily configurable. You may also want some buttons to stop/start the stretch motor when you start your extruder. All that together makes your proposal quite long, and I have no currently no time to do it myself.
Feel free to make a pull request if you successfully implemented it.
