### ISSUE TITLE
TCD1304AP Drive circuit

### ISSUE THREAD

**Issue by onmohd** [superzerg/TCD1304AP_teensy2pp#3]
Hello! Im a researcher at NCSU trying to make a beam displacement sensor, I was reading over this project and was wondering if I need to create the TCD1304AP driven circuit first? When you look in the Toshiba datasheet there is a diagram of a typical driven circuit, that requires a hex inverter, a transistor and a couple of capacitors and resistors, is this still necessary? Since in the project description none of these parts are explicitly mentioned? Also is it possible to threshold the reading received from the ccd, like if the intensity detected is above 2000 for any given pixel, then the magnitude would automatically be set to some value; and if its below 2000 its automatically offset to 0?
Lastly how can i just look at the pure data rather than have some graph output some values, I'm a novice with C++ so if its possible to save the data to a .dat file that would be great.

Thank you

**Comment by superzerg** [comment]
No electronics is needed apart from the the TCD1304 and the teensy2pp.

The C++ code is running on the teensy, it sends the value of each by serial connection to the PC.

The python code (read_pixels.py) is reading that data and is presently only plotting it. It should be very easy to save the data into a file instead or do any transformation such as the one you describe.
