### ISSUE TITLE
python code

### ISSUE THREAD

**Issue by onmohd** [superzerg/TCD1304AP_teensy2pp#4]
Hello, I managed to drive the circuit, but when i run the python code it says that values are being read but the figure isn't being updated, and when i try to click on the figure/graph, the windows freezes and prompts me to exit out, do you know as to why this is happening?

than you

**Comment by superzerg** [comment]
If you look at lines 71-72 of read_pixels.py, you will see that the plot is updated only if the right number of pixels (3648) is received through the serial connection. Try to comment those lines to see what kind of data you are receiving.
